### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

### ISSUE THREAD

**Issue by zouanhao** [AUTOMATIC1111/stable-diffusion-webui-pixelization#25]
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by eCareWebSolutions** [comment]
Check this post, if you're running on an M1 Macbook like me, it fixed my issue.

https://github.com/AUTOMATIC1111/stable-diffusion-webui-pixelization/issues/14#issuecomment-1518890600
